### ISSUE TITLE
HubGay 1.3.2 won't install on Kodi Fire TV Stick (Android OS) FIX FOUND

### ISSUE THREAD

**Issue by Help1ng-Hand** [moedje/kodi-repo-gaymods#5] opened 2019-05-04 06:30 UTC
So I finally figured out why HubGay 1.3.1 installs just fine on Kodi on Fire Stick but 1.3.2 errors out early on in the process saying "the dependency on script.module.urlquick version 0.0.0 cannot be met".

It's because HubGay 1.3.2 requires urlquick as a dependency, but urlquick is blocked from installing because of the platform string in addon.xml (android isn't an included value).
```
kodi-repo-gaymods/script.module.urlquick/addon.xml

original value:  <platform>linux osx windx</platform>
   FIXED value:  <platform>all</platform>
```
Please incorporate this into your next release,

Thanks!

**Comment by moedje** [comment] 2019-05-04 19:55
Thanks very much for pointing this out. As I don’t have a Fire stick and never used one I didn’t realise it wasn’t working. I always rub Kodi on Mac or rPi. 

I will try and incorporate this change. My only question is about the urlquick change is that I didn’t write that addon I simply found it as a tool from another repo so not sure how to tell Kodi to grab the version on my repo so you may need to manually install my updated URLQuick first and the add Hub Gay and hopefully that will work. 

I haven’t been actively developing HUBgay for a while and only just tried it out again last week and found a few sites no longer seem to work so I will try and have another look at getting some of the sites working again if I can. 

Thanks for you help and input nice to know my hobby pet project is being used ;)

**Comment by moedje** [comment] 2019-05-04 21:36
I have now updated urlquick to platform all and updated the version on my repo to 0.9.4 can you try and install this module and HUBGay again and let me know if this now works on Fire Stick? Thanks!

**Comment by Help1ng-Hand** [comment] 2019-05-06 02:27
The new updates seem to be installing OK in Kodi on Fire Stick as well as iPad.

The update methods that worked for me were either manually installing script.module.urlquick-0.9.4.zip , followed by plugin.video.hubgay-1.3.3.zip.

or better yet...

If one does not yet have HubGay installed, or has an Old version such as HubGay 1.3.1, then in Kodi choose:  Install from zip file "repository.kodi-repo-gaymods-2.0.69.zip"
Then choose:  Install from repository >> Gay Addons Repo   moedje - 2.0.69 >> Video add-ons >> HubGay   moedje - 1.3.3

This method also seems to get URLQuick 0.9.4 installed along with HubGay 1.3.3

Thanks again for poking at this project moedje!  HubGay is one of those must-have Addons I like to drop in after installing any Kodi build.

**Comment by Matausi29** [comment] 2020-08-29 01:32
Duplicate of #

**Closed as completed** 2022-06-20 17:29 UTC
